### ISSUE TITLE
Windows installer does not work

### ISSUE THREAD

**Issue by JoseDiazRohena** [sudara/pamplejuce#25] opened 2023-02-26 13:05 UTC
pamplejuce installer runs fine, but does not install a `.vst3` to the desired location. Rather, it installs two files: `unins000.dat` and `unins000`. I first noticed this when checking the installer for my project, which is build from the pamplejuce template. The issue occurs here as well.

**Comment by sudara** [comment] 2023-02-27 20:30
👋 Yes, this is a dupe of #16 

It seems to not always occur, not exactly sure why, maybe depends on windows version.

It could be something very simple in innosetup that needs changing. There's lots of examples online, the next steps are to comb through other audio examples and see what might be missing.

Wanted to look into wix after talking to Timothy about what he set up for https://github.com/plugdata-team/plugdata 

Ultimately there's just not a great solution for windows, that isn't a config/xml nightmare.

Anyway, it'll prob be a few weeks before I need a windows installer again, but I'm open to any pointers (or pull requests!) if you happen to find the issue before that!

**Comment by JoseDiazRohena** [comment] 2023-02-27 20:59
Ah, sorry for the duplication! I'm prioritizing fixing this on my end so I'll for sure let you know if I find a solution. It's odd—I've used the innosetup compiler before and had good results. And I see plenty of examples doing exactly when is in the template.

**Comment by sudara** [comment] 2023-02-27 23:25
No worries!! I thought someone that i talked to said maybe it had to do with using x86-64 specifics instead of just keeping it more generic or something. Sorry, thats probably useless, but i guess maybe some assumptions are made in the config, like what directories might exist or something…. I tried to keep things minimal compared to other things i saw but maybe thats bad…

**Closed** 2023-03-20 15:08 UTC
